[versions]
kotlin = "2.0.20"
paper = "1.21.1-R0.1-SNAPSHOT"
cloud-core = "2.0.0"
cloud-minecraft = "2.0.0-beta.9"

[libraries]

# Gradle plugins

kotlin-jvm = { group = "org.jetbrains.kotlin.jvm", name = "org.jetbrains.kotlin.jvm.gradle.plugin", version.ref = "kotlin" }

# Code dependencies

cloud-core = { group = "org.incendo", name = "cloud-core", version.ref = "cloud-core" }
cloud-paper = { group = "org.incendo", name = "cloud-paper", version.ref = "cloud-minecraft" }
cloud-minecraft-extras = { group = "org.incendo", name = "cloud-minecraft-extras", version.ref = "cloud-minecraft" }
cloud-kotlin-extensions = { group = "org.incendo", name = "cloud-kotlin-extensions", version.ref = "cloud-core" }
cloud-kotlin-coroutines = { group = "org.incendo", name = "cloud-kotlin-coroutines", version.ref = "cloud-core" }

paper = { group = "io.papermc.paper", name = "paper-api", version.ref = "paper" }

[plugins]

shadow = { id = "com.gradleup.shadow", version = "8.3.0" }